### ISSUE TITLE
Update or delete test-page.html?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/addon-wr#30]
### Steps to reproduce:

1. `npm run firefox`
1. Go to <chrome://lookingglass-icons/content/webextension/test-page.html>

### Actual results:

I don't see any substitutions or anything happening.
Not sure if it isn't working w/ latest changes, or maybe I'm using it wrong.

<img width="990" alt="test_page_2" src="https://user-images.githubusercontent.com/557895/33852502-b0869d6c-de6f-11e7-8b77-0c7f055e701b.png">

I'm guessing it isn't working because "chrome://" isn't on the allowed protocols list, but not sure how else to use the test page apart from serving it up using `python -m SimpleHTTPServer` or something similar.

**Comment by gregglind** [comment]
It would show as a `file://` link.

**Comment by gregglind** [comment]
deleted.
