### ISSUE TITLE
You're scaring us

### ISSUE THREAD

**Issue by dessant** [mozilla/addon-wr#36]
![screenshot from 2017-12-13 15-11-24](https://user-images.githubusercontent.com/7513068/33940652-7c15fdca-e018-11e7-9699-b8a3db32470a.png)

The first impression of the add-on listing is terrifying 😋, my first thought was that this may be malware.

Here's a thread of scared people:
https://www.reddit.com/r/firefox/comments/7jh9rv/what_is_looking_glass/

Please add a proper description, and also a `homepage_url` in the manifest, so there will be a reference to further details on the add-on details page.

**Comment by Nefari0uss** [comment]
Yup. I understand I'm using Nightly so stuff will break or randomly appear/disappear but a little bit of a heads up would be nice...

**Comment by dgilman** [comment]
Trust is hard to gain and easy to lose. This was a bad move.

**Comment by 53245342099** [comment]
I don't know what the hell you hope to accomplish with this, but I'm turning off EVERYTHING thanks to you.  Telemetry, shield studies...everything.  I'm hardening up.  I don't know how something like this was ever approved.

**Comment by dtfinch** [comment]
This wasted a half hour of my time, getting installed while I was troubleshooting other problems in Firefox. I had experiments.enabled=false, and 57 re-enabled them without asking.

**Comment by fuckgregglind** [comment]
Very disappointed in Mozilla for allowing this unprofessional 'BS'. Mos of us use Firefox because we care and notice. This is only driving us away.

**Comment by Persola** [comment]
+1 to what @dessant said. Half the trouble is just the lack of a real description.

**Comment by imyxh** [comment]
Yep. This would've been fine with a description, and also, Firefox Studies really needs to indicate that an extension is an official study for sure and not just some random extension.

**Comment by anaran** [comment]
See also https://bugzilla.mozilla.org/show_bug.cgi?id=1424977

**Comment by naoliv** [comment]
And that is how you lose your users, Mozilla.
I had Shield enabled to test new stuff for you and not to have some stupid useless shit enabled.

**Comment by Vednier** [comment]
According to https://github.com/gregglind/addon-wr/blob/master/TESTPLAN.md meaning  of this addon is to "for specific words like privacy and control, they will appear flipped". And there is word "fuck" in this list, for example. 
So, what exactly peoples smoke at Mozilla to make such addons? I just wanna know.

**Comment by imyxh** [comment]
@Vednier I think it was testing content parsing or something. Makes no sense to push it out to everyone, though ... it was probably a mistake.

**Comment by dessant** [comment]
Meanwhile the docs were updated: https://support.mozilla.org/kb/lookingglass.

This is a Mr. Robot promotion pushed out to mostly all Firefox users, since the setting which enables it to be installed is turned on by default.

> SHIELD studies let you try out different features and ideas before they are released to all Firefox users. Using your feedback, we can make more informed decisions based on what you actually need.

https://support.mozilla.org/en-US/kb/shield

SHIELD studies are clearly not meant to be used this way, but it seems to have been a convenient channel for delivering ads. 🥇 

The issue is also tracked here: https://bugzilla.mozilla.org/show_bug.cgi?id=1424977.

**Comment by bogdan-calapod** [comment]
> SHIELD studies are clearly not meant to be used this way, but it seems to have been a convenient channel for delivering ads. 🥇

So some "bright mind" from marketing is behind this "brilliant idea" ? No one in Mozilla ever thought "Guys, does doing marketing that has nothing to do with studies using Studies sound bad to you" ?

**Comment by k32** [comment]
First Quantum, then this. I uninstalled FF from all my computers lately, and, in retrospect, it was a wise decision. GJ Mozilla :(

**Comment by supernintendo** [comment]
Has anyone pointed out the irony of Mozilla claiming to support net neutrality while installing spyware on their users' browsers as part of a promotional campaign for Mr. Robot (owned by Universal, a subsidiary of Comcast)? What a joke.

**Comment by Darkspirit** [comment]
https://twitter.com/steveklabnik/status/942471720954449921
