### ISSUE TITLE
The testplan.md link is a 404

### ISSUE THREAD

**Issue by anaran** [mozilla/addon-wr#41]
See these links:

https://github.com/gregglind/addon-wr/blob/master/testplan.md

  referenced from

https://github.com/gregglind/addon-wr

Details:

The testplan.md link is a 404.

> See ./testplan.md

http://mzl.la/1vxCDgA

**Comment by 153957** [comment]
Filename (not extension) in the link should be in uppercase, and thus link to:
https://github.com/mozilla/addon-wr/blob/master/TESTPLAN.md

**Comment by pdehaan** [comment]
I believe this was fixed via #52.
(Sorry, I don't have admin/collaborator permissions in this repo)
