### ISSUE TITLE
I absolutely did not opt in to this

### ISSUE THREAD

**Issue by datadog23** [mozilla/addon-wr#44]
Are you seriously paying Mozilla to install unasked-for extensions as part of an ARG to promote some TV show I'll never watch?

Have now opted out of their user studies program (being included was on by default), so thanks for possibly making my future browsing experience worse.

Please make the extension's description something descriptive, not an ungrammatical _Matrix_-esque quote a script kid might think was cool

**Comment by MeltedLux** [comment]
cry cry

**Comment by adonig** [comment]
You guys absolutely have lost your minds. People are just coming back from Chrome because of privacy concerns and now you piss them off by installing strange tracking add-ons without their consent. That's how you lose their trust. That's how you lose users to other browsers.

**Comment by supernintendo** [comment]
@MeltedLux Go fuck yourself. Same sentiment goes to Mozilla for pulling this shit.

**Comment by datadog23** [comment]
@MeltedLux One of the most prominent open source projects ever, one i've been using for fifteen years just shot themselves in the foot so incredibly pointlessly, abusing a UX testing system to make it look like i'd been infected with malware, as part of an _ad campaign_? Of course i'm gonna try to tell them i'm annoyed!

**Comment by MeltedLux** [comment]
@supernintendo cry cry

**Comment by htzrd** [comment]
"They won't win. Because one good thing came out of all this. They showed themselves. The top 1% of the 1%. The ones in control. The ones who play god without permission. And now I'm gonna take them down. All of them."
Elliot

Firefox direction and marketing departments didn't had seen the tv show an even trampled the development reams that didn't want this.

**Comment by distransient** [comment]
lmfao you guys need to calm the fuck down

**Comment by fitojb** [comment]
This kind of shit makes me wonder why am I spending my time volunteering for Mozilla, honestly.

**Comment by Darkspirit** [comment]
https://blog.mozilla.org/firefox/update-looking-glass-add/

**Comment by distransient** [comment]
like a bunch of you are -1'ing me but have all of you considered how useless and volatile it is to take out your frustration by harassing the issue tracker of some random folk that probably weren't even involved in the decision process. grow the fuck up

**Comment by SharpOB** [comment]
The "random folk" in charge of this is a Mozilla Employee. Him having to deal with this is a method of raising it to Mozilla's attention, which is good. They need to see this outrage on all fronts.

Grow the fuck up.

**Comment by distransient** [comment]
...I need to grow up because I'm saying people shouldn't go onto Github and throw tantrums on issue trackers because it makes them feel better. Okay, for sure dude. LOL

**Comment by SharpOB** [comment]
Reread my comment - it seems you didn't read it, and just looked at the last sentence.

**Comment by distransient** [comment]
I did read your comment. Did you read mine?

**Comment by jonhoo** [comment]
@gregglind this thread should probably be locked at this point.

**Comment by gregglind** [comment]
Alas, probably so.

**Comment by jonhoo** [comment]
@gregglind closing it is not sufficient as it does not prevent further comments. You'd have to also lock it to prevent that.
