### ISSUE TITLE
i missed a detailed explanation

### ISSUE THREAD

**Issue by muescha** [mozilla/addon-wr#54]
i missed a detailed explanation:
- what this addon do
- what it changed
- how i can "play" with it
- why and which data is send to this sites:
```
const XHEADERSITES = [
  "https://www.red-wheelbarrow.com/forkids/*",
  "https://www.whatismybrowser.com/detect/*",
  "https://red-wheelbarrow-stage.apps.nbcuni.com/forkids/*",
];
```

**Comment by gregglind** [comment]
1.  These effects are listed in [./TESTPLAN.md](./TELEMETRY.md), and [./TELEMETRY.md](./TELEMETRY.md).
2.  Short answer:  Data collected - no additional data collection. Other sites on the web will continue to collect whatever they collect.  
3.  Short answer regarding effects:  No content effects, unless you turned on the preference by hand.  If the preference is on, an additional header is sent to those listed websites.  If the preference is on, content in websites is modified such that some words (from a list, related to the themes of Mr. Robot) will display upside down briefly.
4. This version is no longer installed / available.  If you want to use the webExtension version (1.0.5):  https://addons.mozilla.org/en-US/firefox/addon/looking-glass/.  That version will act as though the "preference is true".  

I hope this satisfies your questions!
